language: node_js
node_js:
  - 0.8
notifications:
  email: false
env:
  global:
    - secure: MFYd1vQcnuqepxEzU6khzQF6MXmqHAmaAfnrOuxx3kXkycD5yCWM6bqAPN8MEy0epCK5MpGTTwYSIx+US07UrsceAzPt6TNCBK+8meycKXe/8sflBBf5ZzgTR8V8qB1EWcOSBH5JbS9uNYQx8riqtOsOHdRp/2VnPDRObKojOow=
    - secure: Ecxw3myTw3ucJJfJTBFnYj5k22fbDrgmOAh47orN2GeVAkudqduBrlsU0Quh7c3J5BxyE3f70bCpGT8BiewPtUAf7kdCLc37OFRQq6mV0ci2VmyyJvC5hDCZRrQkAf8I9gDWb2kqduSd7cJKvZcLjCZY4/y9DxhrFPmerabJzKs=
